export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIES_FINISHED = "FETCH_MOVIES_FINISHED";
export const FETCH_MOVIES_ERROR = "FETCH_MOVIES_ERROR";

export const FETCH_MOVIE_DETAILS = "FETCH_MOVIE_DETAILS";
export const FETCH_MOVIE_DETAILS_FINISHED = "FETCH_MOVIE_DETAILS_FINISHED";
export const FETCH_MOVIE_DETAILS_ERROR = "FETCH_MOVIE_DETAILS_ERROR";

export const FETCH_MORE_MOVIES = "FETCH_MORE_MOVIES";
export const FETCH_MORE_MOVIES_FINISHED = "FETCH_MORE_MOVIES_FINISHED";
export const FETCH_MORE_MOVIES_ERROR = "FETCH_MORE_MOVIES_ERROR";

export const FETCH_SUGGESTION = "FETCH_SUGGESTION";
export const FETCH_SUGGESTION_FINISHED = "FETCH_SUGGESTION_FINISHED";
export const FETCH_SUGGESTION_ERROR = "FETCH_SUGGESTION_ERROR";
